spring:
  application:
    name: demo

  datasource:
#    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
